### ISSUE TITLE
请教个问题~

### ISSUE THREAD

**Issue by sjkhsl** [semicons/java_oci_manage#1]
ubuntu20.04安装oci-cli报错，大佬知道怎么解决吗？

===> Currently supported optional packages are: ['db (will install cx_Oracle)']
What optional CLI packages would you like to be installed (comma separated names; press enter if you don't need any optional packages)?: 
-- The optional packages installed will be ''.
-- Executing: ['', 'apt-get', 'update']
-- System was unable to use venv, is going to download and create virtualenv.
-- Downloading virtualenv package from https://github.com/pypa/get-virtualenv/blob/20.6.0/public/virtualenv.pyz?raw=true.
-- Downloaded virtualenv package to /tmp/tmpjj_a73ll/virtualenv-20.6.0.pyz.
-- Checksum of /tmp/tmpjj_a73ll/virtualenv-20.6.0.pyz OK.
-- Executing: ['/usr/bin/python3', 'virtualenv-20.6.0.pyz', '/root/lib/oracle-cli']
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "virtualenv-20.6.0.pyz/__main__.py", line 168, in <module>
  File "virtualenv-20.6.0.pyz/__main__.py", line 164, in run
  File "virtualenv-20.6.0.pyz/virtualenv/__main__.py", line 18, in run
  File "virtualenv-20.6.0.pyz/virtualenv/run/__init__.py", line 32, in cli_run
  File "virtualenv-20.6.0.pyz/virtualenv/run/session.py", line 46, in run
  File "virtualenv-20.6.0.pyz/virtualenv/run/session.py", line 53, in _create
  File "virtualenv-20.6.0.pyz/virtualenv/create/creator.py", line 171, in run
  File "virtualenv-20.6.0.pyz/virtualenv/create/via_global_ref/builtin/via_global_self_do.py", line 79, in create
  File "virtualenv-20.6.0.pyz/virtualenv/create/via_global_ref/builtin/via_global_self_do.py", line 104, in ensure_directories
  File "virtualenv-20.6.0.pyz/virtualenv/create/describe.py", line 29, in bin_dir
  File "virtualenv-20.6.0.pyz/virtualenv/create/describe.py", line 33, in script_dir
  File "virtualenv-20.6.0.pyz/virtualenv/discovery/py_info.py", line 125, in install_path
  File "virtualenv-20.6.0.pyz/virtualenv/discovery/py_info.py", line 125, in <dictcomp>
ValueError: too many values to unpack (expected 2)
Traceback (most recent call last):
  File "/tmp/oci_cli_install_tmp_s6rB", line 257, in create_virtualenv
    install_python3_venv()
  File "/tmp/oci_cli_install_tmp_s6rB", line 204, in install_python3_venv
    exec_command(cmd)
  File "/tmp/oci_cli_install_tmp_s6rB", line 141, in exec_command
    subprocess.check_call(command_list, cwd=cwd, env=env)
  File "/usr/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/oci_cli_install_tmp_s6rB", line 722, in <module>
    main()
  File "/tmp/oci_cli_install_tmp_s6rB", line 668, in main
    create_virtualenv(tmp_dir, install_dir)
  File "/tmp/oci_cli_install_tmp_s6rB", line 271, in create_virtualenv
    download_and_create_virtualenv(tmp_dir, install_dir)
  File "/tmp/oci_cli_install_tmp_s6rB", line 196, in download_and_create_virtualenv
    exec_command(cmd, cwd=working_dir)
  File "/tmp/oci_cli_install_tmp_s6rB", line 141, in exec_command
    subprocess.check_call(command_list, cwd=cwd, env=env)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'virtualenv-20.6.0.pyz', '/root/lib/oracle-cli']' returned non-zero exit status 1.

**Comment by semicons** [comment]
本系统不需要oci cli
