### ISSUE TITLE
升级6.0启动报错

### ISSUE THREAD

**Issue by onepve** [semicons/java_oci_manage#30]
上个版本正常使用,早上看到升级就升级了一下,然后....配置文件无变动
```
即将查看日志,请稍后(按【ctrl+c】可退出日志)
2024-07-21 07:55:19.321 - request error:syntax error : 102
2024-07-21 07:55:19.321 - 启动失败，错误信息：syntax error : 102
2024-07-21 07:55:19.321 - 无azure配置，跳过
```

**Comment by afghn** [comment]
哥们，一样

**Comment by tomkint** [comment]
同样报错，求助

**Comment by semicons** [comment]
使用一键脚本回退旧版即可，新版已归pre测试中

**Comment by alexallen1** [comment]
> 使用一键脚本回退旧版即可，新版已归pre测试中
使用最新一键脚本
wget -O sh_client_bot.sh https://github.com/semicons/java_oci_manage/releases/latest/download/sh_client_bot.sh && chmod +x sh_client_bot.sh && bash sh_client_bot.sh


一样om.alibaba.fastjson2.JSONException,message:syntax error : 102

一键脚本，执行了，没有回退旧版功能啊

**Comment by semicons** [comment]
> > 使用一键脚本回退旧版即可，新版已归预测试中
> > 使用最新一键脚本
> > wget -O sh_client_bot.sh https://github.com/semicons/java_oci_manage/releases/latest/download/sh_client_bot.sh && chmod +x sh_client_bot.sh && bash sh_client_bot.sh
> 
> 类似 om.alibaba.fastjson2.JSONException，消息：语法错误：102
> 
> debian12 x86 阿里香港域名复现
> 
> 一键脚本，执行了，没有回退旧版功能啊

已经升级为最新版了，旧版无法回退，可以看一下你本地的日志把完整的错误信息贴一下。

**Comment by alexallen1** [comment]
> > > 使用一键脚本回退旧版即可，新版已归预测试中
> > > 使用最新一键脚本
> > > wget -O sh_client_bot.sh https://github.com/semicons/java_oci_manage/releases/latest/download/sh_client_bot.sh && chmod +x sh_client_bot.sh && bash sh_client_bot.sh
> > 
> > 
> > 类似 om.alibaba.fastjson2.JSONException，消息：语法错误：102
> > debian12 x86 阿里香港域名复现
> > 一键脚本，执行了，没有回退旧版功能啊
> 
> 已经升级为最新版了，旧版无法回退，可以看一下你本地的日志把完整的错误信息贴一下。


之前正常的。点击显示现在绑定的域名也正常显示
```
2024-09-08 04:41:06.106 - 服务正在启动，请稍后...
2024-09-08 16:58:46.923 - oracle配置获取成功 -> 当前profile为:迪拜
旧ip:139.185
新ip：84.235
2024-09-08 16:59:11.885 - 更换绑定域名报错
com.alibaba.fastjson2.JSONException: syntax error : 102
  at com.alibaba.fastjson2.JSONReaderUTF8.readBoolValue(JSONReaderUTF8.java:7518)
  at com.alibaba.fastjson2.JSONReader.readObject(JSONReader.java:2310)
  at com.alibaba.fastjson2.JSONReader.readArray(JSONReader.java:2565)
  at com.alibaba.fastjson2.JSONReader.read(JSONReader.java:2092)
  at com.alibaba.fastjson2.JSON.parseObject(JSON.java:348)
  at com.alibaba.fastjson2.JSONObject.parseObject(JSONObject.java:2052)
  at com.semicons.github.servies.CFApiService.sendRequest(CFApiService.java:96)
  at com.semicons.github.servies.CFApiService.getZone(CFApiService.java:78)
  at com.semicons.github.servies.DomainService.handleDomain(DomainService.java:89)
  at com.semicons.github.servies.DomainService.dealDomains(DomainService.java:163)
  at com.semicons.github.web.M.lambda$updatePublicIp$88(M.java:2394)
  at java.base@21.0.4/java.lang.Thread.runWith(Thread.java:1596)
  at java.base@21.0.4/java.lang.VirtualThread.run(VirtualThread.java:329)
  at java.base@21.0.4/java.lang.VirtualThread$VThreadContinuation$1.run(VirtualThread.java:209)
```

**Comment by semicons** [comment]
> > > > 使用一键脚本回退旧版即可，新版已归预测试中
> > > > 使用最新一键脚本
> > > > wget -O sh_client_bot.sh https://github.com/semicons/java_oci_manage/releases/latest/download/sh_client_bot.sh && chmod +x sh_client_bot.sh && bash sh_client_bot.sh
> > > 
> > > 
> > > 类似 om.alibaba.fastjson2.JSONException，消息：语法错误：102
> > > debian12 x86 阿里香港域名复现
> > > 一键脚本，执行了，没有回退旧版功能啊
> > 
> > 
> > 已经升级为最新版了，旧版无法回退，可以看一下你本地的日志把完整的错误信息贴一下。
> 
> 之前正常的。点击显示现在绑定的域名也正常显示
> 
> ```
> 2024-09-08 04:41:06.106 - 服务正在启动，请稍后...
> 2024-09-08 16:58:46.923 - oracle配置获取成功 -> 当前profile为:迪拜
> 旧ip:139.185
> 新ip：84.235
> 2024-09-08 16:59:11.885 - 更换绑定域名报错
> com.alibaba.fastjson2.JSONException: syntax error : 102
>   at com.alibaba.fastjson2.JSONReaderUTF8.readBoolValue(JSONReaderUTF8.java:7518)
>   at com.alibaba.fastjson2.JSONReader.readObject(JSONReader.java:2310)
>   at com.alibaba.fastjson2.JSONReader.readArray(JSONReader.java:2565)
>   at com.alibaba.fastjson2.JSONReader.read(JSONReader.java:2092)
>   at com.alibaba.fastjson2.JSON.parseObject(JSON.java:348)
>   at com.alibaba.fastjson2.JSONObject.parseObject(JSONObject.java:2052)
>   at com.semicons.github.servies.CFApiService.sendRequest(CFApiService.java:96)
>   at com.semicons.github.servies.CFApiService.getZone(CFApiService.java:78)
>   at com.semicons.github.servies.DomainService.handleDomain(DomainService.java:89)
>   at com.semicons.github.servies.DomainService.dealDomains(DomainService.java:163)
>   at com.semicons.github.web.M.lambda$updatePublicIp$88(M.java:2394)
>   at java.base@21.0.4/java.lang.Thread.runWith(Thread.java:1596)
>   at java.base@21.0.4/java.lang.VirtualThread.run(VirtualThread.java:329)
>   at java.base@21.0.4/java.lang.VirtualThread$VThreadContinuation$1.run(VirtualThread.java:209)
> ```

更新6.0.9已经修复
