### ISSUE TITLE
脚本报错求解

### ISSUE THREAD

**Issue by wlqb2001** [semicons/java_oci_manage#34]
root@hcss-ecs-51b8:~# tail -f log_r_client.log  
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:113)
        at java.base@21.0.5/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base@21.0.5/java.lang.Thread.runWith(Thread.java:1596)
        at java.base@21.0.5/java.lang.VirtualThread.run(VirtualThread.java:329)
        at java.base@21.0.5/java.lang.VirtualThread$VThreadContinuation$1.run(VirtualThread.java:209)
2024-12-05 19:44:14.900 - 地区：eu-frankfurt-1运行出错,但程序已继续运行,请检查错误信息后和实例数量再决定是否终止执行,错误信息为：(-1, null, true) jakarta.ws.rs.ProcessingException: java.net.UnknownHostException: iaas.eu-frankfurt-1.oraclecloud.com: Try again (outbound opc-request-id: 529B1848CA82471CBCC8F3A1A88F861E)

**Comment by semicons** [comment]
-1为你的服务器到甲骨文服务器连接超时，导致的问题，尝试重启几次或者更换服务器
